# if: tag IS present

language: python

env:
  global:
    - PORT=7000
    - port=8000
    - DOCKER_REPO=streamlink-service
    - HEROKU_REPO=juststream

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/$DOCKER_REPO .
  - pip install pytest-cov pytest-flake8 codecov
  - openssl aes-256-cbc -K $encrypted_7c88188abb27_key -iv $encrypted_7c88188abb27_iv -in streamlink-1-1a849fdf22dd.json.enc -out streamlink-1-1a849fdf22dd.json -d

install:
  - docker run -d -e PORT=$PORT -p $port:$PORT $DOCKER_USERNAME/$DOCKER_REPO

script:
  - python -m pytest
  - git clean -fd

deploy:
  - provider: script
    script: ./deploy.sh
    on:
      all_branches: true
  - provider: gae
    project: streamlink-1
    keyfile: streamlink-1-1a849fdf22dd.json.enc
