name: main

on: [workflow_dispatch]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPO: streamlink-service
  PORT: 7000
  entry: 8000

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: build
        run: docker build -t $DOCKER_USERNAME/$DOCKER_REPO .
      - name: install
        run: pip install pytest-cov pytest-flake8 codecov
      - name: run
        run: docker run -d -e PORT=$PORT -p $entry:$PORT $DOCKER_USERNAME/$DOCKER_REPO
      - name: test
        run: sleep 4; python -m pytest
      - name: deploy
        env:
          BOV_API_KEY: ${{ secrets.BOV_API_KEY }}
          BOV_IDENTITY: ${{ secrets.BOV_IDENTITY }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          JUSTSTREAM_API_KEY: ${{ secrets.JUSTSTREAM_API_KEY }}
          JUSTSTREAM_IDENTITY: ${{ secrets.JUSTSTREAM_IDENTITY }}
          VOM_API_KEY: ${{ secrets.VOM_API_KEY }}
          VOM_IDENTITY: ${{ secrets.VOM_IDENTITY }}
        run: ./deploy.sh
