name: main

on: [workflow_dispatch]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -t $DOCKER_USERNAME/streamlink-service .
      - name: deployment
        env:
          BOV_API_KEY: ${{ secrets.BOV_API_KEY }}
          BOV_IDENTITY: ${{ secrets.BOV_IDENTITY }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          JUSTSTREAM_API_KEY: ${{ secrets.JUSTSTREAM_API_KEY }}
          JUSTSTREAM_IDENTITY: ${{ secrets.JUSTSTREAM_IDENTITY }}
          VOM_API_KEY: ${{ secrets.VOM_API_KEY }}
          VOM_IDENTITY: ${{ secrets.VOM_IDENTITY }}
        run: ./deploy.sh
